name: "🚀 Publish package to GitHub package registry / NPM"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
        - main

jobs:
    release:
        name: "😇 publish"
        runs-on: ubuntu-latest
        steps:
          - name: "🤓 checkout"
            uses: actions/checkout@v2
          - name: "Node environment set up"
            uses: actions/setup-node@v2
            with:
              node-version: 12
              registry-url: https://registry.npmjs.com
          - name: "🚀 publish"
            run: npm publish
            working-directory: deploy/dist
            env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
